### ISSUE TITLE
Not compatible with 1.0

### ISSUE THREAD

**Issue by bsun0000** [Epicguru/WhatsThatMod#1]
Literally. 
Assembly targets 4.5 framework (1.0 rimworld still uses 3.5), 
Main project refers to stuff like UnityEngine.IMGUIModule.dll - it does not exist in 1.0; UnityEngine is old, 5.6.x,
ModCore.cs calls to unimplemented functions like ModLister.GetActiveModWithIdentifier..

I suggest you to remove 1.0 tag from supported versions to not confuse players.

**Comment by Epicguru** [comment]
Done, thanks for reporting.
