### ISSUE TITLE
Ideology creation window offset OOB

### ISSUE THREAD

**Issue by orbittwz** [Epicguru/WhatsThatMod#4]
as mentioned in 
https://discord.com/channels/214523379766525963/257987178834034688/947826665281699870

the mod doesn't insert a word onto the next line, but still carriage return the whole block, hiding the first line of words outside the frame boundaries.
would like this to be fixed :)
![image](https://user-images.githubusercontent.com/45605734/155982626-e0361751-47dd-470a-9c03-f5723f0db04b.png)
modded above...
![image](https://user-images.githubusercontent.com/45605734/155982700-512c9c56-108b-4e6e-864e-729282bb1c91.png)
vanilla above...

**Comment by Epicguru** [comment]
This isn't really a bug per-se but a flaw in the UI system.
![image](https://user-images.githubusercontent.com/26253331/155983846-29d38726-bce9-417b-a465-2662da5a7888.png)
There is an invisible box (in green) and the text is centered vertically within that box. When the *Ideology* tag is added to the bottom it increases the height of the text. This means that when the text is centered, it pushes the top and bottom outside of the invisible box and they are cut off.

There is no simple solution to this as it is an inherit limitation of the UI system. One fix would be to remove the line gap in the mod settings to make the text less tall. The real fix would be to go through the game UI and patch all these text boxes to be able to scroll, but I'm sure you understand that I can't do that.

**Comment by orbittwz** [comment]
pretty sure you can add the word "Ideology" without carriage return, specifically for the first frame there...
the word will be just after the last word... you can space that if you want.

**Comment by Epicguru** [comment]
Like I mentioned that can be done by changing the mod settings. Go to the menu -> Mod Options -> What's That Mod -> Change the number of 'blank lines'. It looks like you have it set to 1 blank line. You can change it to zero.

**Comment by orbittwz** [comment]
setting it to 0 would make the mod write the names near each object last words...
kinda disorienting imo
not possible to code this specifically just for this frame?

**Comment by Epicguru** [comment]
It is not possible to change where the text is placed on a particular screen. Descriptions are edited once, when the game is loading.

**Comment by orbittwz** [comment]
![image](https://user-images.githubusercontent.com/45605734/155988852-02d7f9d2-ceb7-45a5-904f-1eb5903c2963.png)
here's the window after I removed the last sentence, looks like the mod does write the name in the same frame, but you can't see it...

**Comment by orbittwz** [comment]
btw, i don't have blank lines in the mod's settings...
![image](https://user-images.githubusercontent.com/45605734/155989170-8131b4ca-7da7-4405-8432-f42119d39c72.png)

**Comment by orbittwz** [comment]
my guess if I'm trying to patch this frame for your mod, is this...
![image](https://user-images.githubusercontent.com/45605734/155990390-1364a55d-3d0a-43e9-a286-3dc8cd3536f4.png)
